### ISSUE TITLE
0.3.0 breaks Rust 2018 style macro imports

### ISSUE THREAD

**Issue by yvt** [nvzqz/static-assertions-rs#10]
The following code no longer compiles as of 0.3.0:

```rust
use static_assertions::const_assert;

fn main() {
    const_assert!(true);
}
```

```
error: cannot find macro `_const_assert!` in this scope
 --> src/main.rs:4:5
  |
4 |     const_assert!(true);
  |     ^^^^^^^^^^^^^^^^^^^^ help: you could try the macro: `const_assert`
  |
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

Related: https://github.com/rust-lang-nursery/lazy-static.rs/pull/107

**Comment by nvzqz** [comment]
Should be fixed with commit c2dd597

**Comment by gin-ahirsch** [comment]
Commit d5994b64752c08cf5bda1d7bd13e595095b672d9 broke this again.

**Comment by nvzqz** [comment]
@gin-ahirsch OP's example works for me with 1.0. What error are you getting?

**Comment by gin-ahirsch** [comment]
Ah indeed, `const_assert!` does work. `assert_qe_size_val!` does not though: `error: cannot find macro `assert_eq_size_ptr!` in this scope`.

**Comment by nvzqz** [comment]
Ah, so my doc tests didn't catch that because I `#[macro_use]`-ed the crate, which imports all macros. I'll update my tests to `use` macros to catch things like this going forward. I actually caught this same error when writing `assert_impl_one!` (added in https://github.com/nvzqz/static-assertions-rs/pull/23).
